<?php

return [
    [
        'icon' => '📊',
        'label' => 'Dashboard',
        'route' => 'admin.dashboard',
    ],
    [
        'icon' => '👥',
        'label' => 'Users',
        'items' => [
            ['label' => 'All Users', 'route' => 'admin.users.index'],
            'Roles & Permissions',
            'User Verification',
            'User Activity',
            'Login History',
        ],
    ],
    [
        'icon' => '🎬',
        'label' => 'AI Ad Studio',
        'items' => [
            'Ad Projects',
            'Image Generations',
            'Video Generations',
            'Ad Copy Generations',
            'Brand Kits',
            'Templates',
            'Asset Library',
        ],
    ],
    [
        'icon' => '🤖',
        'label' => 'AI Engine',
        'items' => [
            'AI Providers',
            'Image Models',
            'Video Models',
            'Copywriting Models',
            'Prompt Templates',
            'Style Presets',
            'Safety Moderation',
            'API Keys',
        ],
    ],
    [
        'icon' => '💳',
        'label' => 'Billing',
        'items' => [
            'Overview',
            'Pricing Plans',
            'Orders',
            'Subscriptions',
            'Invoices',
            'Payment Gateways',
            'Taxes',
            'Coupons',
            'Finance Settings',
        ],
    ],
    [
        'icon' => '💰',
        'label' => 'Credits & Usage',
        'items' => [
            'Credits Overview',
            'Credit Packages',
            'Credit Transactions',
            'Usage Limits',
            'AI API Usage',
            'Cost Tracking',
            'Failed Generations',
        ],
    ],
    [
        'icon' => '📈',
        'label' => 'Analytics',
        'items' => [
            'Revenue',
            'Users',
            'Conversions',
            'Generation Analytics',
            'Model Usage',
            'Campaign Performance',
            'Server Status',
        ],
    ],
    [
        'icon' => '🎫',
        'label' => 'Support',
        'items' => [
            'Tickets',
            'FAQ',
            'Contact Messages',
            'Abuse Reports',
        ],
    ],
    [
        'icon' => '📢',
        'label' => 'Marketing',
        'items' => [
            'Notifications',
            'Email Campaigns',
            'Push Notifications',
            'Testimonials',
            'Blog',
            'SEO',
            'Google Adsense',
        ],
    ],
    [
        'icon' => '🎨',
        'label' => 'Appearance',
        'items' => [
            'Themes',
            'Logos',
            'Pages',
            'Menus',
            'Homepage Builder',
            'Footer',
            'Custom CSS',
            'Custom JS',
        ],
    ],
    [
        'icon' => '⚙️',
        'label' => 'Settings',
        'items' => [
            'General',
            'Localization',
            'Languages',
            'Authentication',
            'Registration',
            'SMTP',
            'Storage',
            'Security',
            'GDPR',
            'API',
            'Cron Jobs',
            'Cache',
            'System Information',
        ],
    ],
    [
        'icon' => '🔌',
        'label' => 'Extensions',
        'items' => [
            'Plugins',
            'Integrations',
            'Webhooks',
        ],
    ],
    [
        'icon' => '📝',
        'label' => 'Logs',
        'items' => [
            'Activity Logs',
            'Error Logs',
            'Audit Logs',
            'Login Logs',
            'AI Generation Logs',
            'Webhook Logs',
        ],
    ],
    [
        'icon' => '🔄',
        'label' => 'Maintenance',
        'items' => [
            'Updates',
            'Backups',
            'Import / Export',
            'Maintenance Mode',
        ],
    ],
];
