<?php

return [
    [
        'icon' => '📊',
        'label' => 'Dashboard',
        'route' => 'admin.dashboard',
    ],
    [
        'icon' => '👥',
        'label' => 'Users',
        'items' => [
            ['label' => 'All Users', 'route' => 'admin.users.index'],
            'Roles & Permissions',
            'User Verification',
            'User Activity',
            'Login History',
        ],
    ],
    [
        'icon' => '💳',
        'label' => 'Billing',
        'items' => [
            'Overview',
            'Pricing Plans',
            'Orders',
            'Subscriptions',
            'Invoices',
            'Payment Gateways',
            'Taxes',
            'Coupons',
            'Finance Settings',
        ],
    ],
    [
        'icon' => '💰',
        'label' => 'Finance',
        'items' => [
            'Earnings',
            'Transactions',
            'Payouts',
            'Withdraw Requests',
            'Affiliate Program',
        ],
    ],
    [
        'icon' => '🏪',
        'label' => 'Marketplace',
        'items' => [
            'Listings',
            'Categories',
            'Reviews',
            'Reports',
            'Featured Listings',
        ],
    ],
    [
        'icon' => '🎫',
        'label' => 'Support',
        'items' => [
            'Tickets',
            'FAQ',
            'Contact Messages',
        ],
    ],
    [
        'icon' => '📢',
        'label' => 'Marketing',
        'items' => [
            'Notifications',
            'Email Campaigns',
            'Push Notifications',
            'Testimonials',
            'Blog',
            'SEO',
            'Google Adsense',
        ],
    ],
    [
        'icon' => '🎨',
        'label' => 'Appearance',
        'items' => [
            'Themes',
            'Logos',
            'Pages',
            'Menus',
            'Homepage Builder',
            'Footer',
            'Custom CSS',
            'Custom JS',
        ],
    ],
    [
        'icon' => '🤖',
        'label' => 'AI',
        'items' => [
            'AI Providers',
            'Models',
            'Prompt Templates',
            'Usage Limits',
            'Credits',
            'API Keys',
        ],
    ],
    [
        'icon' => '⚙️',
        'label' => 'Settings',
        'items' => [
            'General',
            'Localization',
            'Languages',
            'Authentication',
            'Registration',
            'SMTP',
            'Storage',
            'Security',
            'GDPR',
            'API',
            'Cron Jobs',
            'Cache',
            'System Information',
        ],
    ],
    [
        'icon' => '🔌',
        'label' => 'Extensions',
        'items' => [
            'Plugins',
            'Integrations',
            'Webhooks',
        ],
    ],
    [
        'icon' => '📈',
        'label' => 'Analytics',
        'items' => [
            'Revenue',
            'Users',
            'Conversions',
            'API Usage',
            'Server Status',
        ],
    ],
    [
        'icon' => '📝',
        'label' => 'Logs',
        'items' => [
            'Activity Logs',
            'Error Logs',
            'Audit Logs',
            'Login Logs',
        ],
    ],
    [
        'icon' => '🔄',
        'label' => 'Maintenance',
        'items' => [
            'Updates',
            'Backups',
            'Import / Export',
            'Maintenance Mode',
        ],
    ],
];
